### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by arm64x** [woyehenni/ipatool#2]
Hi, after setup I can't login bro

[info] Logging in with provided information...

 ERROR  [xmldom error]	invalid doc source 
@#[line:0,col:undefined]

 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'address')

**Comment by icemmw** [comment]
same error when I use npm

**Comment by kerwinzxc** [comment]
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'address')
  at Object.handler (./chunks/routes/api/auth/login.post.mjs:33:38)  
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)  
  at async Object.handler (./chunks/runtime.mjs:3092:19)  
  at async toNodeHandle (./chunks/runtime.mjs:3362:7)  
  at async Server.<anonymous> (/opt/rust/nodejs.js:16:5674)
